### PR TITLE
Navigation bar

### PR DESCRIPTION
**Pull request by Mexolius**
Simple navbar, i might have messed up the required components but changing the names is very quick

### CODE REVIEW

**Review by piotrpolec — COMMENTED** [review]
Czy package.json nie powinien być w git ignorze? Przez to pokazuje że dodałeś 20k lini kodu

**Comment by grzanka** [comment]
> Czy package.json nie powinien być w git ignorze? Przez to pokazuje że dodałeś 20k lini kodu

use English, please

**Comment by grzanka** [comment]
> Czy package.json nie powinien być w git ignorze? Przez to pokazuje że dodałeś 20k lini kodu

Check this answer
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by piotrpolec** [comment]
> > Czy package.json nie powinien być w git ignorze? Przez to pokazuje że dodałeś 20k lini kodu
> 
> Check this answer
> https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

Okay, thanks

**Review by piotrpolec — APPROVED** [review]

**Comment by Mexolius** [comment]
There was some problem with dependencies, luckly, it is resolved now, however, i don't think this is recoverable since package-lock.json is like a change-log, you shouldn't remove anything from it. That said, the amount of work to reproduce what's been done on this branch is much less than trying to save it, so i will just write it again from master.

**Pull request closed without merging**
