### PR TITLE
Deployment fix

### PR DESCRIPTION
**Pull request by Mexolius**
Allows for deploying the build to github pages using npm run deploy. Aditionally fiexd some minor recat rendering issues.

### CODE REVIEW

**Comment by grzanka** [comment]
Tests are still failing:
image

**Review by piotrpolec — COMMENTED** [review]
Mergable if the tests pass

**Comment by grzanka** [comment]
> Mergable if the tests pass

Tests still failing:
```
found 84 vulnerabilities (82 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
/home/runner/work/_temp/0a53aca6-166a-4bb8-b9a9-628b1282d092.sh: line 2: gh-pages: command not found
Error: Process completed with exit code 127.
```

See https://github.com/APTG/dedx_web/pull/62/checks?check_run_id=2978727561

**Comment by Mexolius** [comment]
So in the end it works, but it needs permissions to write to web_dev repo

**Comment by grzanka** [comment]
> So in the end it works, but it needs permissions to write to web_dev repo

So what should we do now ?

**Comment by Mexolius** [comment]
I think we could arrange a meeting to resolve this, I think it's just the matter of granting permissions and maybe setting one secret in the web_dev repo

**Review by grzanka — APPROVED** [review]

**Pull request merged**
