### PR TITLE
Site navigation + footer

### PR DESCRIPTION
**Pull request by Mexolius**
Also includes react side of version tracking (commit number, date and branch) which was requested in issue #55

### CODE REVIEW

**Comment by Mexolius** [comment]
Tests are failing. I will remove them from now and try to reasonably cover the whole app with tests on a separate branch

**Comment by grzanka** [comment]
> Tests are failing. I will remove them from now and try to reasonably cover the whole app with tests on a separate branch

No problem.

Is this PR ready for review ? If not mark it as draft

**Comment by Mexolius** [comment]
It's ready to review. The DeepSource integration requires some major refactoring so i believe it should be done on a separate branch as well

**Review by grzanka — APPROVED** [review]
Looks good

**Pull request merged**
