### PR TITLE
Add bootstrap to the project

### PR DESCRIPTION
**Pull request by piotrpolec**

### CODE REVIEW

**Comment by grzanka** [comment]
Is it ready for review ?

**Comment by grzanka** [comment]
@piotrpolec there are many conflicts

**Comment by grzanka** [comment]
When testing on gitpod I got:

```
Failed to compile.

SyntaxError: /workspace/dedx_web/src/Components/ContentWrapper.js: Expected corresponding JSX closing tag for <Router>. (62:16)
  60 |                         </div>
  61 |                     </div>
> 62 |                 </div>
     |                 ^
  63 |             </Router>
  64 |         );
  65 |     }
assets by path static/ 1.55 MiB
  asset static/js/bundle.js 1.53 MiB [emitted] (name: main) 1 related asset
  asset static/media/github-logo.746ec8f0bc97208f903e.png 12.7 KiB [emitted] [immutable] [from: src/Components/Footer/github-logo.png] (auxiliary name: main)
  asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.88 KiB [emitted] 1 related asset
asset index.html 1.72 KiB [emitted]
asset asset-manifest.json 596 bytes [emitted]
runtime modules 31.4 KiB 16 modules
modules by path ./node_modules/ 1.38 MiB 95 modules
modules by path ./src/ 22.1 KiB (javascript) 12.7 KiB (asset)
  javascript modules 22 KiB
    modules by path ./src/*.css 8.84 KiB 4 modules
    modules by path ./src/*.js 4.64 KiB 3 modules
    modules by path ./src/Components/ 4.42 KiB 3 modules
    modules by path ./src/Styles/*.css 4.08 KiB
      ./src/Styles/Footer.css 2.77 KiB [built] [code generated]
      ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/Styles/Footer.css 1.31 KiB [built] [code generated]
  ./src/Components/Footer/deploy.json 81 bytes [built] [code generated]
  ./src/Components/Footer/github-logo.png 42 bytes (javascript) 12.7 KiB (asset) [built] [code generated]

ERROR in ./src/Components/ContentWrapper.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /workspace/dedx_web/src/Components/ContentWrapper.js: Expected corresponding JSX closing tag for <Router>. (62:16)

  60 |                         </div>
  61 |                     </div>
> 62 |                 </div>
     |                 ^
  63 |             </Router>
  64 |         );
  65 |     }
    at Object._raise (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:569:17)
    at Object.raiseWithData (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:562:17)
    at Object.raise (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:523:17)
    at Object.jsxParseElementAt (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:7478:16)
    at Object.jsxParseElement (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:7504:17)
    at Object.parseExprAtom (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:7518:19)
    at Object.parseExprSubscripts (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:11654:23)
    at Object.parseUpdate (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:11634:21)
    at Object.parseMaybeUnary (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:11609:23)
    at Object.parseMaybeUnaryOrPrivate (/workspace/dedx_web/node_modules/@babel/parser/lib/index.js:11421:61)
 @ ./src/Components/Main.js 4:0-46 15:37-51
 @ ./src/App.js 6:0-37 11:35-39
 @ ./src/index.js 7:0-24 11:33-36

ERROR in src/Components/ContentWrapper.js
  Line 62:16:  Parsing error: Expected corresponding JSX closing tag for <Router>. (62:16)

webpack 5.65.0 compiled with 2 errors in 7512 ms
^C
gitpod /workspace/dedx_web $ 
```

**Comment by grzanka** [comment]
Buttons to change scale on X and Y axis looks weird now, are you planning to fix it in this or next PR ?

image

**Comment by Mexolius** [comment]
working to fix that

**Comment by grzanka** [comment]
> working to fix that

great, but in which branch ? would you like to merge this PR first and fix that later ?

**Comment by Mexolius** [comment]
fixed, hopefully

**Review by grzanka — APPROVED** [review]
LGTM

**Pull request merged**
